pipeline:
  build:
    image: node:6.12
    commands:
      - npm run install:api
      - npm run build:api
      - npm run install:web
      - npm run build:web
      # - npm run install:desktop
      # - npm run build:desktop
      # - npm run test:api

  api-image:
    image: plugins/docker
    dockerfile: api/Dockerfile
    repo: mhsallam/reporthubapi
    secrets: [ docker_username, docker_password ]

  web-image:
    image: plugins/docker
    dockerfile: web/Dockerfile
    repo: mhsallam/reporthubweb
    secrets: [ docker_username, docker_password ]
      
#   # api-rancher:
#   #   image: peloton/drone-rancher
#   #   url: http://35.154.69.25:8080
#   #   access_key: serverKey
#   #   secret_key: serverPass
#   #   service: ReportHub/api
#   #   docker_image: mhsallam/reporthubapi

  deploy-containers:
    image: appleboy/drone-ssh
    host: 52.90.0.221
    port: 22
    username: ubuntu
    secrets: [ ssh_key ]
    script:
      - docker rm $(docker stop $(docker ps -a -q --filter="name=reporthub" --format="{{.ID}}"))
      - docker run -it -p 81:3000 --name reporthub-api mhsallam/reporthubapi
      - docker run -it -p 80:3000 --name reporthub-web mhsallam/reporthubweb

  depoly-faas:
    image: mhsallam/bxcli
    secrets: [ bluemix_user, bluemix_password, bluemix_account, bluemix_org ]
    commands:
      - echo  $${BLUEMIX_USER}
      - bx login -u $${BLUEMIX_USER} -p $${BLUEMIX_PASSWORD} -c $${BLUEMIX_ACCOUNT} -a api.eu-gb.bluemix.net -o $${BLUEMIX_ORG} -s dev
      - bx target -g Default
      - bx wsk action update reports ./services/reports/reports.js

  gitter:
    image: plugins/gitter
    webhook: https://webhooks.gitter.im/e/d93462d24fbcff832c6d