pipeline:
  api:
    image: plugins/docker
    context: api
    dockerfile: api/Dockerfile
    repo: mhsallam/rhapi
    secrets: [ docker_username, docker_password ]

  web-ng:
    image: plugins/docker 
    context: web-ng
    dockerfile: web-ng/Dockerfile
    repo: mhsallam/rhwebng
    secrets: [ docker_username, docker_password ]

  deploy-containers:
    image: appleboy/drone-ssh
    host: 52.90.0.221
    port: 22
    username: ubuntu
    secrets: [ ssh_key ]
    script:
      - git clone https://github.com/iMMAP/rh
      - chmod +x rh/scripts/reset-cont.sh && rh/scripts/reset-cont.sh
      - docker run -it -p 8001:3000 -d --name reporthub-api mhsallam/rhapi
      - docker run -it -p 8002:4200 -d --name reporthub-web mhsallam/rhwebng
      # - docker run -it -p 8002:4200 -d --name reporthub-web mhsallam/rhweb
      # - rm -cf ./rh && git clone https://github.com/iMMAP/rh.git && cd rh
      # - npm run install:desktop
      # - npm run build:desktop
      # - cd desktop/dist/

  # depoly-faas:
  #   image: mhsallam/bxcli
  #   secrets: [ bluemix_user, bluemix_password, bluemix_account, bluemix_org ]
  #   commands:
  #     - echo  $${BLUEMIX_USER}
  #     - bx login -u $${BLUEMIX_USER} -p $${BLUEMIX_PASSWORD} -c $${BLUEMIX_ACCOUNT} -a api.eu-gb.bluemix.net -o $${BLUEMIX_ORG} -s dev
  #     - bx target -g Default
  #     - bx wsk action update reports ./services/reports/reports.js

  gitter:
    image: plugins/gitter
    webhook: https://webhooks.gitter.im/e/d93462d24fbcff832c6d