version: '2'

services:
  drone-server:
    image: drone/drone

    ports:
      - 8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=mhsallam,drfaustusfade,fakhrihawari,pfitzpaddy
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=8826f2b348bee7a73e4b
      - DRONE_GITHUB_SECRET=53a024cc51f0d1f27a56aad51d913bc2618f22c4
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}